added two OAS rules for AEP-131
aep-dev/aep-openapi-linter pull request #5
Opened 2024-08-24 01:38 UTC by rambleraptor

This adds rules to verify that a resource is being returned + the operation ID begins with get

2024-08-26 16:16 UTC, toumorokoshi commented on src/ruleset.ts
> +            message: "The response body does not include an AEP resource.",
is it worth linking to the specific guidance?

2024-08-26 16:21 UTC, toumorokoshi requested changes
code looks good! I'm primarily concerned with codifying operationIDs: https://github.com/aep-dev/aep.dev/issues/208.

2024-08-26 16:21 UTC, toumorokoshi commented on src/ruleset.ts
> +            given: "$.paths[*].get.responseBody.content[application/json].schema",
we wiil overlook this check if the content type isn't application/json, is that ok? I guess we document that we should accept application/json, but we don't officially require it in the bullets below: https://aep.dev/131#requests.

2024-08-26 16:21 UTC, toumorokoshi commented on src/ruleset.ts
> +            message: "The operation ID does not conform to AEP-131",
I wanted to revisit operationIDs and make sure we had the right syntax for those: https://github.com/aep-dev/aep.dev/issues/208. Could we wait on this?

2025-01-10 17:42 UTC, mkistler commented
Closing this out as it has been covered by #10.

2025-01-10 17:42 UTC, closed without merging